# Generated by Django 4.2.6 on 2023-10-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=60)),
                ('uf', models.PositiveSmallIntegerField()),
                ('lat_lon', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('ibge_id', models.PositiveSmallIntegerField()),
                ('country', models.PositiveSmallIntegerField()),
                ('ddd', models.JSONField()),
                ('teste', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('hometown', models.PositiveSmallIntegerField()),
                ('visited_cities', models.JSONField()),
                ('interested_cities', models.JSONField()),
                ('planning_cities', models.JSONField()),
                ('regenerate_map', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('path', models.TextField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
    ]
