# Generated by Django 4.2.6 on 2023-10-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_state_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='state',
            name='ibge_id',
        ),
    ]
