# Generated by Django 4.2.6 on 2023-10-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_city_cod_tom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
    ]
