# Generated by Django 4.2.6 on 2023-10-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_photo_city_id_remove_photo_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=60)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
                ('lat_lon', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cod_tom', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('path', models.TextField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
