# Generated by Django 4.2.6 on 2023-10-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_city_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
