# Generated by Django 4.2.6 on 2023-10-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
