# Generated by Django 4.2.6 on 2023-10-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0014_remove_photo_city_id_remove_photo_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_id', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=60)),
                ('lat_lon', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cod_tom', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('ibge_id', models.PositiveSmallIntegerField()),
                ('country_id', models.PositiveSmallIntegerField()),
                ('ddd', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('hometown', models.PositiveSmallIntegerField()),
                ('visited_cities', models.JSONField()),
                ('interested_cities', models.JSONField()),
                ('planning_cities', models.JSONField()),
                ('regenerate_map', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('path', models.TextField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
    ]
