# Generated by Django 4.2.6 on 2023-10-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_state_hometown_alter_state_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
