# Generated by Django 4.2.6 on 2023-10-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_user_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regenerate_map',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
