# Generated by Django 4.2.6 on 2023-10-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_regenerate_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regenerate_map',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
