# Generated by Django 4.2.6 on 2023-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_userdetails_alter_interestedcities_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='state_hometown',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
