# Generated by Django 4.2.6 on 2023-10-28 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_alter_userdetails_state_hometown'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestedCities',
            new_name='InterestedCity',
        ),
        migrations.RenameModel(
            old_name='PlanningCities',
            new_name='PlanningCity',
        ),
        migrations.RenameModel(
            old_name='VisitedCities',
            new_name='VisitedCity',
        ),
    ]
